# Generated by Django 4.2.9 on 2024-02-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Вид алкоголя')),
                ('slug', models.SlugField(blank=True, max_length=30, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Вид алкоголя',
                'verbose_name_plural': 'Виды алкоголя',
            },
        ),
        migrations.CreateModel(
            name='Whiskey_characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('brand', models.CharField(blank=True, max_length=60, null=True, verbose_name='Бренд')),
                ('country', models.CharField(blank=True, max_length=60, null=True, verbose_name='Страна производства')),
                ('vid', models.CharField(blank=True, max_length=60, null=True, verbose_name='Вид напитка')),
                ('taste', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вкус')),
                ('favor', models.CharField(blank=True, max_length=250, null=True, verbose_name='Аромат')),
                ('excerpt', models.CharField(blank=True, max_length=150, null=True, verbose_name='Выдержка')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Объем, мл')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='Крепость (% об.)')),
                ('fats', models.CharField(blank=True, max_length=60, null=True, verbose_name='Жиры')),
                ('carbohydrates', models.CharField(blank=True, max_length=60, null=True, verbose_name='Углеводы')),
                ('proteins', models.CharField(blank=True, max_length=60, null=True, verbose_name='Белки')),
                ('calorie_content_kcal', models.CharField(blank=True, max_length=60, null=True, verbose_name='Калорийность ккал')),
                ('humidity', models.CharField(blank=True, max_length=60, null=True, verbose_name='Влажность')),
                ('storage_temperature', models.CharField(blank=True, max_length=60, null=True, verbose_name='Температура хранения')),
                ('expiration_date', models.CharField(blank=True, max_length=60, null=True, verbose_name='Срок годности')),
                ('storage_conditions', models.CharField(blank=True, max_length=60, null=True, verbose_name='Условия хранения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='photos/Виски/%Y/%m/%d/', verbose_name='Изображение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Виски',
                'verbose_name_plural': 'Виски',
            },
        ),
        migrations.CreateModel(
            name='Vodka_characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('brand', models.CharField(max_length=60, verbose_name='Бренд')),
                ('country', models.CharField(blank=True, max_length=60, null=True, verbose_name='Страна-производитель товара')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объем, л')),
                ('amount_in_box', models.IntegerField(blank=True, null=True, verbose_name='Штук в ящике')),
                ('vid', models.CharField(blank=True, max_length=60, null=True, verbose_name='Вид')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='Крепость')),
                ('excerpt', models.CharField(blank=True, max_length=60, null=True, verbose_name='Выдержка')),
                ('supply_temperature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Температура подачи')),
                ('taste', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вкус')),
                ('color', models.CharField(blank=True, max_length=60, null=True, verbose_name='Цвет')),
                ('coctails', models.CharField(blank=True, max_length=150, null=True, verbose_name='Коктейли')),
                ('gastronomic_compatibility', models.CharField(blank=True, max_length=200, null=True, verbose_name='Гастрономическая сочетаемость')),
                ('sizes', models.CharField(blank=True, max_length=60, null=True, verbose_name='Размеры, см')),
                ('weight', models.CharField(blank=True, max_length=60, null=True, verbose_name='Вес, кг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='photos/Водка/%Y/%m/%d/', verbose_name='Изображение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Водка',
                'verbose_name_plural': 'Водка',
            },
        ),
        migrations.CreateModel(
            name='Vine_characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('color', models.CharField(blank=True, max_length=60, null=True, verbose_name='Цвет')),
                ('country', models.CharField(blank=True, max_length=60, null=True, verbose_name='Страна')),
                ('alcogol_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Алкоголь')),
                ('type', models.CharField(blank=True, max_length=60, null=True, verbose_name='Тип')),
                ('brand', models.CharField(blank=True, max_length=60, null=True, verbose_name='Бренд')),
                ('sugar', models.CharField(blank=True, max_length=60, null=True, verbose_name='Сахар')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион')),
                ('style', models.CharField(blank=True, max_length=60, null=True, verbose_name='Стиль')),
                ('sort', models.CharField(blank=True, max_length=60, null=True, verbose_name='Сорт')),
                ('classification', models.CharField(blank=True, max_length=150, null=True, verbose_name='Классификация')),
                ('image', models.ImageField(upload_to='photos/Вино/%Y/%m/%d/', verbose_name='Изображение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вино',
                'verbose_name_plural': 'Вино',
            },
        ),
        migrations.CreateModel(
            name='Cognak_characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('code', models.CharField(max_length=10, verbose_name='Код товара')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Объем')),
                ('brand', models.CharField(max_length=60, verbose_name='Бренд')),
                ('country', models.CharField(max_length=60, verbose_name='Страна')),
                ('strength', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Крепость')),
                ('excerpt', models.CharField(blank=True, max_length=60, null=True, verbose_name='Выдержка')),
                ('production_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зона производства')),
                ('serving_temperature', models.IntegerField(blank=True, null=True, verbose_name='Температура сервировки')),
                ('favor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Аромат')),
                ('taste', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вкус')),
                ('gastronomic_combination', models.CharField(blank=True, max_length=150, null=True, verbose_name='Гастрономическое сочетание')),
                ('features_of_the_technology', models.CharField(blank=True, max_length=200, null=True, verbose_name='Особенности технологии')),
                ('sort', models.CharField(blank=True, max_length=150, null=True, verbose_name='Сорт винограда')),
                ('image', models.ImageField(upload_to='photos/Коньяк/%Y/%m/%d/', verbose_name='Изображение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Коньяк',
                'verbose_name_plural': 'Коньяк',
            },
        ),
        migrations.CreateModel(
            name='Beer_characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('country_color_vid', models.CharField(max_length=150, verbose_name='Страна, цвет, вид')),
                ('strength', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Крепость')),
                ('bitterness', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Горечь')),
                ('density', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Плотность')),
                ('favor', models.CharField(max_length=400, verbose_name='Аромат')),
                ('taste', models.CharField(max_length=400, verbose_name='Вкус')),
                ('aftertaste', models.CharField(max_length=400, verbose_name='Послевкусие')),
                ('composition', models.CharField(max_length=400, verbose_name='Композиция')),
                ('is_combined', models.CharField(max_length=400, verbose_name='С чем сочетается')),
                ('country', models.CharField(max_length=60, verbose_name='Страна')),
                ('type', models.CharField(max_length=60, verbose_name='Тип')),
                ('vid', models.CharField(max_length=60, verbose_name='Вид')),
                ('color', models.CharField(max_length=60, verbose_name='Цвет')),
                ('image', models.ImageField(upload_to='photos/Пиво/%Y/%m/%d/', verbose_name='Изображение')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пиво',
                'verbose_name_plural': 'Пиво',
            },
        ),
    ]
